[package]
name = "ghommit"
version = "0.0.5"
edition = "2021"

[profile.release]
strip = "debuginfo"

[dependencies]
base64 = "0.21.0"
clap = { version = "4.2.4", features = ["derive"] }
colored = "2.0.0"
git2 = "0.17.1"
jsonwebtoken = "8.3.0"
openssl = { version = "0.10.52", features = ["vendored"] }
once_cell = "1.17.1"
regex = "1.8.1"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0.96"
time = "0.3.21"

[dev-dependencies]
base16ct = { version = "0.2.0", features = ["alloc"] }
sha-1 = "0.10.1"
tempfile = "3.5.0"
