[package]
name = "ghommit"
version = "0.0.4"
edition = "2021"

[dependencies]
base64 = "0.21.0"
clap = { version = "4.2.4", features = ["derive"] }
git2 = "0.17.1"
jsonwebtoken = "8.3.0"
once_cell = "1.17.1"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0.96"

[dev-dependencies]
base16ct = { version = "0.2.0", features = ["alloc"] }
sha-1 = "0.10.1"
tempfile = "3.5.0"
